name: Deploy to GitHub Pages

# This 'on' block replaces GitLab's 'rules'
on:
  # Run this job only for pushes to the 'main' or 'master' branch
  push:
    branches:
      - main
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Set permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # This 'build' job is like the first part of your 'pages' job
  build:
    name: Build
    runs-on: ubuntu-latest
    
    # This 'env' block replaces GitLab's 'variables'
    env:
      UV_VERSION: 0.5
      PYTHON_VERSION: 3.12
      BASE_LAYER: bookworm-slim
      UV_LINK_MODE: copy

    # This 'container' block replaces GitLab's 'image'
    container:
      image: ghcr.io/astral-sh/uv:${{ env.UV_VERSION }}-python${{ env.PYTHON_VERSION }}-${{ env.BASE_LAYER }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run export script
        # This 'run' step replaces GitLab's 'script'
        run: |
          # Note: I'm using '-o public' to match your GitLab 'artifacts: paths: - public'
          uv run marimo export html-wasm draw_pos.py -o public --mode edit

      - name: Upload artifact
        # This action replaces GitLab's 'artifacts' block
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the 'public' directory
          path: 'public'

  # This 'deploy' job finishes the process and deploys to GitHub Pages
  deploy:
    name: Deploy to Pages
    needs: build # This job runs only after the 'build' job succeeds
    runs-on: ubuntu-latest

    # Specify the deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4